"""Expose the public package surface for docport."""

__version__ = "1.0.0"

from docport.adapters import (
    AsyncMongoStore,
    MongoDocumentMapper,
    MongoStore,
    StoreDependencyError,
    StoreInfrastructureError,
)
from docport.domain import (
    DEFAULT_ENTITY_VERSION,
    DEFAULT_TIME_SERIES_FIELD_NAME,
    METADATA_FIELD_NAMES,
    DocPortEntity,
    DocPortError,
    DocPortTimeSeriesEntity,
    DocumentId,
    DuplicateEntityError,
    EntityNotFoundError,
    EntityVersionConflictError,
    FindOptions,
    ObservationOutcome,
    Projection,
    ProjectionDocument,
    SortDirection,
    SortField,
    StoreConfigurationError,
    StoreDocument,
    StoreFilter,
    StoreObservation,
    StoreOperationContext,
    StoreSort,
    new_correlation_id,
    new_entity_id,
    utc_now,
)
from docport.ports import (
    AsyncStore,
    NoOpStoreObservabilityHook,
    Store,
    StoreObservabilityHook,
    StorePort,
)

__all__ = [
    "AsyncMongoStore",
    "MongoDocumentMapper",
    "MongoStore",
    "StoreDependencyError",
    "StoreInfrastructureError",
    "DEFAULT_ENTITY_VERSION",
    "DEFAULT_TIME_SERIES_FIELD_NAME",
    "METADATA_FIELD_NAMES",
    "DocumentId",
    "DuplicateEntityError",
    "EntityNotFoundError",
    "EntityVersionConflictError",
    "FindOptions",
    "ObservationOutcome",
    "Projection",
    "ProjectionDocument",
    "SortDirection",
    "SortField",
    "StoreObservation",
    "StoreConfigurationError",
    "StoreDocument",
    "StoreFilter",
    "StoreOperationContext",
    "StoreSort",
    "DocPortError",
    "DocPortEntity",
    "DocPortTimeSeriesEntity",
    "new_correlation_id",
    "new_entity_id",
    "utc_now",
    "AsyncStore",
    "NoOpStoreObservabilityHook",
    "Store",
    "StoreObservabilityHook",
    "StorePort",
    "__version__",
]
